import type { ComplaintRecord, TechnicianRecord, VendorRecord } from '../types'

export const complaintRecords: ComplaintRecord[] = [
  {
    id: 'CMP-2041',
    title: 'Main server room cooling issue',
    campus: 'Campus',
    department: 'IT Infrastructure',
    status: 'New',
    priority: 'High',
    vendor: 'XY Facilities',
    technician: 'Amit Yadav',
    createdDate: '11 Mar 2026',
  },
  {
    id: 'CMP-2037',
    title: 'Biotech lab router packet loss',
    campus: 'Campus',
    department: 'IT Infrastructure',
    status: 'In Review',
    priority: 'High',
    vendor: 'XY Facilities',
    technician: 'Unassigned',
    createdDate: '11 Mar 2026',
  },
  {
    id: 'CMP-2032',
    title: 'Hostel C water line maintenance',
    campus: 'North Campus',
    department: 'Civil Works',
    status: 'Assigned',
    priority: 'Medium',
    vendor: 'Z1 Maintenance',
    technician: 'Riya Nanda',
    createdDate: '10 Mar 2026',
  },
  {
    id: 'CMP-2026',
    title: 'Admin block access control sync failure',
    campus: 'Campus',
    department: 'Security Operations',
    status: 'Escalated',
    priority: 'High',
    vendor: 'XY Facilities',
    technician: 'Amit Yadav',
    createdDate: '09 Mar 2026',
  },
  {
    id: 'CMP-2018',
    title: 'Library lighting panel fault',
    campus: 'Research Park',
    department: 'Electrical Maintenance',
    status: 'Resolved',
    priority: 'Low',
    vendor: 'Prime Infra',
    technician: 'Sneha Verma',
    createdDate: '08 Mar 2026',
  },
  {
    id: 'CMP-2011',
    title: 'Seminar hall projection console diagnostics',
    campus: 'Research Park',
    department: 'AV Support',
    status: 'New',
    priority: 'Medium',
    vendor: 'Prime Infra',
    technician: 'Unassigned',
    createdDate: '07 Mar 2026',
  },
]

export const vendorRecords: VendorRecord[] = [
  {
    id: 'VEN-1',
    name: 'XY Facilities',
    campus: 'Campus',
    category: 'Electrical and surveillance maintenance',
    activeTickets: 14,
    slaScore: 96,
    lastAudit: '08 Mar 2026',
  },
  {
    id: 'VEN-2',
    name: 'Z1 Maintenance',
    campus: 'North Campus',
    category: 'Civil and water supply operations',
    activeTickets: 11,
    slaScore: 92,
    lastAudit: '07 Mar 2026',
  },
  {
    id: 'VEN-3',
    name: 'Prime Infra',
    campus: 'Research Park',
    category: 'HVAC and plant utility services',
    activeTickets: 7,
    slaScore: 88,
    lastAudit: '05 Mar 2026',
  },
]

export const technicianRecords: TechnicianRecord[] = [
  {
    id: 'TEC-1',
    name: 'Amit Yadav',
    campus: 'Research Park',
    department: 'Civil Works',
    assignedTasks: 12,
    completionRate: 78,
    risk: 'High',
  },
  {
    id: 'TEC-2',
    name: 'Riya Nanda',
    campus: 'North Campus',
    department: 'Administration',
    assignedTasks: 9,
    completionRate: 91,
    risk: 'Moderate',
  },
  {
    id: 'TEC-3',
    name: 'Sneha Verma',
    campus: 'Campus',
    department: 'Plumbing Maintenance',
    assignedTasks: 6,
    completionRate: 94,
    risk: 'Low',
  },
]
