import type { PermissionCategory, RoleDefinition } from '../types'

export const permissionCategories: PermissionCategory[] = [
  { category: 'Identity', permissions: ['USER_CREATE', 'USER_EDIT', 'USER_DELETE'] },
  { category: 'Roles', permissions: ['ROLE_EDIT'] },
  { category: 'Sessions', permissions: ['FORCE_LOGOUT'] },
  { category: 'Governance', permissions: ['VIEW_AUDIT', 'SYSTEM_SETTINGS_EDIT'] },
  { category: 'Super Admin', permissions: ['USER_IMPERSONATE', 'REPORTS_VIEW', 'ANALYTICS_VIEW'] },
]

export const roleRecords: RoleDefinition[] = [
  {
    id: 'ROLE-01',
    key: 'SUPER_ADMIN',
    name: 'Super Admin',
    owner: 'Central Admin Dashboard',
    members: 4,
    policy: 'Full control with change audit enforcement',
    conflictStatus: 'Clear',
    coverage: 100,
    permissions: {
      USER_CREATE: true,
      USER_EDIT: true,
      USER_DELETE: true,
      ROLE_EDIT: true,
      FORCE_LOGOUT: true,
      VIEW_AUDIT: true,
      SYSTEM_SETTINGS_EDIT: true,
      USER_IMPERSONATE: true,
      REPORTS_VIEW: true,
      ANALYTICS_VIEW: true,
    },
  },
  {
    id: 'ROLE-02',
    key: 'SECURITY_ADMIN',
    name: 'Security Admin',
    owner: 'Security Office',
    members: 7,
    policy: 'Audit and access governance with limited destructive actions',
    conflictStatus: 'Needs Review',
    coverage: 82,
    permissions: {
      USER_CREATE: true,
      USER_EDIT: true,
      USER_DELETE: false,
      ROLE_EDIT: true,
      FORCE_LOGOUT: true,
      VIEW_AUDIT: true,
      SYSTEM_SETTINGS_EDIT: false,
      USER_IMPERSONATE: false,
      REPORTS_VIEW: true,
      ANALYTICS_VIEW: true,
    },
  },
  {
    id: 'ROLE-03',
    key: 'OPS_ADMIN',
    name: 'Operations Admin',
    owner: 'Campus Operations',
    members: 18,
    policy: 'Operational oversight with no system-level governance editing',
    conflictStatus: 'Clear',
    coverage: 64,
    permissions: {
      USER_CREATE: false,
      USER_EDIT: true,
      USER_DELETE: false,
      ROLE_EDIT: false,
      FORCE_LOGOUT: false,
      VIEW_AUDIT: false,
      SYSTEM_SETTINGS_EDIT: false,
      USER_IMPERSONATE: false,
      REPORTS_VIEW: true,
      ANALYTICS_VIEW: true,
    },
  },
]
