export const userAccessFeatureKey = 'user-access'

export { default as AdminShell } from './components/layout/AdminShell'
export { default as DashboardPage } from './pages/admin/Dashboard'
export { default as UserManagementPage } from './pages/admin/UserManagement'
export { default as RoleMatrixPage } from './pages/admin/RoleMatrix'
export { default as SessionsPage } from './pages/admin/Sessions'
export { default as ComplaintMonitoringPage } from './pages/admin/ComplaintMonitoring'
export { default as VendorsPage } from './pages/admin/VendorOverview'
export { default as TechniciansPage } from './pages/admin/TechnicianOverview'
export { default as ReportsPage } from './pages/admin/Reports'
export { default as AnalyticsPage } from './pages/admin/Analytics'
export { default as AuditLogsPage } from './pages/admin/AuditLogs'
export { default as ActivityLogsPage } from './pages/admin/ActivityLogs'
export { default as NotificationCenterPage } from './pages/admin/NotificationCenter'
export { default as SettingsPage } from './pages/admin/SystemSettings'
